### PR TITLE
Implement bought and sold command

### PR DESCRIPTION
**Pull request by ITZXITZX**
Work In Progress. 
Have only updated implementation of bought command and statistics class in AddressBook.
Yet to implement test cases and the sold command

### CODE REVIEW

**Review by triishaa — COMMENTED** [review]
The English in the documentation can be improved. Maybe use 
"Formats the {@code Properties} to be displayed to the user"

**Review by triishaa — CHANGES_REQUESTED** [review]
Update the documentation in BoughtPropertyCommandParser class. Its currently w.r.t the AddPropertyToBuyCommand

**Review by triishaa — CHANGES_REQUESTED** [review]
Shouldn't use * imports. Can it be a potential violation of coding standards?

**Comment by ITZXITZX** [comment]
I have sent another PR after addressing requests for changes

**Pull request closed without merging**
